name: Build S9+ DerpFest KernelSU Next Boot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1


      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            bc bison build-essential curl flex git wget \
            libssl-dev libelf-dev \
            python3 unzip zip cpio rsync \
            gcc-aarch64-linux-gnu


      - name: Clone AOSP Clang
        run: |
          git clone --depth=1 \
          https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 \
          -b android-11.0.0_r48 clang


      - name: Setup KernelSU Next
        run: |
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -


      - name: Build Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64

          export PATH=$PWD/clang/clang-r383902/bin:$PATH

          mkdir -p out

          make O=out exynos9810-star2lte_defconfig

          make -j$(nproc) \
            O=out \
            CC=clang \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-gnu-


      - name: Create Image.gz-dtb
        run: |
          cat \
          out/arch/arm64/boot/Image.gz \
          out/arch/arm64/boot/dts/exynos/exynos9810-star2lte_eur_open_26.dtb \
          > out/arch/arm64/boot/Image.gz-dtb


      - name: Repack DerpFest boot.img
        run: |
          git clone --depth=1 \
          https://github.com/osm0sis/AnyKernel3.git AK3

          chmod +x AK3/tools/magiskboot

          mkdir bootwork

          cp boot.img bootwork/

          cd bootwork

          ../AK3/tools/magiskboot unpack boot.img

          cp ../out/arch/arm64/boot/Image.gz-dtb kernel

          ../AK3/tools/magiskboot repack boot.img

          mv new-boot.img ../S9Plus-DerpFest-A13-KernelSU-Next.img


      - name: Upload Final boot.img
        uses: actions/upload-artifact@v4
        with:
          name: S9Plus-DerpFest-A13-KernelSU-Next-boot
          path: S9Plus-DerpFest-A13-KernelSU-Next.img
